// import './instance/index.js'
// import './data-banding/index.js'
// import './computed/index.js'
// import './directive/index.js'
// import './component/define.js'
// import './component/extend.js'
// import './component/v-model.js'
// import './component/feature.js'
import './component/render.js'
